[phases.setup]
  runtime = "python-3.10.12"

[phases.build]
  commands = ["pip install -r requirements.txt"]

[phases.start]
  commands = ["python manage.py migrate", "python manage.py runserver 0.0.0.0:8000"]
