[phases.setup]
  runtime = "python-3.9.16"  # Adjust if a different Python version is needed

[phases.build]
  commands = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.start]
  commands = ["python manage.py migrate", "python manage.py runserver 0.0.0.0:8000"]