# Generated by Django 5.1 on 2024-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_todo_text_todo_category_todo_name_todo_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
